---
- name: Install Apache Web Server and upload index.html
  hosts: all
  become: yes

  vars:
    src_file: index.html
    dst_file: /var/www/html

  tasks:

  - name: Check Linux distro
    debug:
      var: ansible_os_family

  - name: Install Apache Web Server on RedHat Family
    yum:
      name: httpd
      state: latest
    when: ansible_os_family == "RedHat"

  - name: Install Apache Web Server on Debian Family
    apt:
      update_cache: yes
      name: apache2
      state: latest
    when:
      ansible_os_family == "Debian"

  - name: Upload site content to the servers
    copy:
      src: "{{ src_file }}"
      dest: "{{ dst_file }}"
      mode: 0555
    #notify: Restart Apache

  - name: Start and enable Apache on RedHat Family
    service:
      name: httpd
      state: started
      enabled: yes
    when:
      ansible_os_family == "RedHat"

  - name: Start and enable Apache on Debian Family
    service:
      name: apache2
      state: started
      enabled: yes
    when:
      ansible_os_family == "Debian"

  handlers:
  - name: Restart Apache
    service:
      name: httpd
      state: restarted
