---
- name: Install Apache Web Server on Amazon Linux
  hosts: all
  become: yes

  tasks:
  - name: Instal Apache Web Server
    yum:
      name: httpd
      state: latest

  - name: Start and enable the service
    service:
      name: httpd
      state: started
      enabled: yes
