---
- name: Install Apache Web Server and upload web page content
  hosts: all
  become: yes

  vars:
    src_dir: ./MyWebSite
    dst_dir: /var/www/html

  tasks:

  - name: Check Linux distro
    debug:
      var: ansible_os_family

  - block:  # RedHat

    - name: Install Apache Web Server on RedHat Family
      yum:
        name: httpd
        state: latest

    - name: Start and enable Apache on RedHat Family
      service:
        name: httpd
        state: started
        enabled: yes

    when:
      ansible_os_family == "RedHat"

  - block:  # Debian

    - name: Install Apache Web Server on Debian Family
      apt:
        update_cache: yes
        name: apache2
        state: latest

    - name: Start and enable Apache on Debian Family
      service:
        name: apache2
        state: started
        enabled: yes

    when:
      ansible_os_family == "Debian"

  - name: Generate and upload index.html
    template:
      src: "{{ src_dir }}/index.html.j2"
      dest: "{{ dst_dir }}/index.html"
      mode: 0555
    notify:
      - Restart Apache Debian
      - Restart Apache RedHat

  - name: Upload photo.png
    copy:
      src: "{{ src_dir }}/photo.png"
      dest: "{{ dst_dir }}"
      mode: 0555
    notify:
      - Restart Apache Debian
      - Restart Apache RedHat

  handlers:
  - name: Restart Apache RedHat
    service:
      name: httpd
      state: restarted
    when:
      ansible_os_family == "RedHat"

  - name: Restart Apache Debian
    service:
      name: apache2
      state: restarted
    when:
      ansible_os_family == "Debian"
